// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJCY0Ghd4h4wZQBzKhMCYlfc_TeSibCvQ',
    appId: '1:19381538023:web:e6131796ce3ca7d185a642',
    messagingSenderId: '19381538023',
    projectId: 'tugas12flutter-sanbercode',
    authDomain: 'tugas12flutter-sanbercode.firebaseapp.com',
    storageBucket: 'tugas12flutter-sanbercode.appspot.com',
    measurementId: 'G-9CX7GSE0HY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTadxp3PAXd0K43Z33qdaeuI7UCq4lZK0',
    appId: '1:19381538023:android:e7d23471e044cad885a642',
    messagingSenderId: '19381538023',
    projectId: 'tugas12flutter-sanbercode',
    storageBucket: 'tugas12flutter-sanbercode.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvcLP71G4vIVmjQqRTcftVdqq4O4DE7Tg',
    appId: '1:19381538023:ios:b9c9bf6196796dee85a642',
    messagingSenderId: '19381538023',
    projectId: 'tugas12flutter-sanbercode',
    storageBucket: 'tugas12flutter-sanbercode.appspot.com',
    iosBundleId: 'com.example.tugas12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvcLP71G4vIVmjQqRTcftVdqq4O4DE7Tg',
    appId: '1:19381538023:ios:b9c9bf6196796dee85a642',
    messagingSenderId: '19381538023',
    projectId: 'tugas12flutter-sanbercode',
    storageBucket: 'tugas12flutter-sanbercode.appspot.com',
    iosBundleId: 'com.example.tugas12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJCY0Ghd4h4wZQBzKhMCYlfc_TeSibCvQ',
    appId: '1:19381538023:web:92b9bfd3046e054285a642',
    messagingSenderId: '19381538023',
    projectId: 'tugas12flutter-sanbercode',
    authDomain: 'tugas12flutter-sanbercode.firebaseapp.com',
    storageBucket: 'tugas12flutter-sanbercode.appspot.com',
    measurementId: 'G-76LXNYPTDX',
  );
}
